// Common Indian educational institutions
export const COLLEGES = [
  "Indian Institute of Science (IISc)",
  "Indian Institute of Technology Bombay (IIT Bombay)",
  "Indian Institute of Technology Delhi (IIT Delhi)",
  "Indian Institute of Technology Madras (IIT Madras)",
  "Indian Institute of Technology Kanpur (IIT Kanpur)",
  "Indian Institute of Technology Kharagpur (IIT Kharagpur)",
  "Jawaharlal Nehru University (JNU)",
  "Delhi University (DU)",
  "Banaras Hindu University (BHU)",
  "Anna University",
  "University of Hyderabad",
  "Jadavpur University",
  "Aligarh Muslim University (AMU)",
  "Savitribai Phule Pune University",
  "University of Calcutta",
  "Mumbai University",
  // Bengaluru Colleges
  "Indian Institute of Science Education and Research (IISER)",
  "National Institute of Mental Health and Neurosciences (NIMHANS)",
  "National Law School of India University (NLSIU)",
  "Bangalore University",
  "Christ University",
  "Mount Carmel College",
  "St. Joseph's College",
  "Jain University",
  "PES University",
  "RV College of Engineering",
  "BMS College of Engineering",
  "MS Ramaiah Institute of Technology",
  "Bangalore Institute of Technology",
  "NITTE Meenakshi Institute of Technology",
  "Dayananda Sagar College of Engineering",
  "CMR Institute of Technology",
  "New Horizon College of Engineering",
  "Sir M Visvesvaraya Institute of Technology",
  "East Point College of Engineering and Technology",
  "Garden City University",
  "Reva University",
  "Presidency University",
  "ISE Bangalore",
  "IIM Bangalore",
  "Indian Institute of Science (IISc) Bangalore",
  "National Institute of Fashion Technology (NIFT) Bangalore",
  "Indian Institute of Astrophysics",
  "National Centre for Biological Sciences (NCBS)",
  "St. John's Medical College",
  "Bangalore Medical College and Research Institute",
];

// Major Indian cities
export const CITIES = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
];

// Indian states and union territories
export const STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];